spring:
  rabbitmq:
    host: 192.168.232.145
    port: 5672
    username: admin
    password: 123456
    # 交换机中的消息确认类型（无论是否成功发布到RabbitMQ中，都会回调RabbitTemplate.ConfirmCallback的confirm方法）
    publisher-confirm-type: correlated
    # 开启消息回退，当消息投递不出去，路由失败，就会回退消息给生产者
    publisher-returns: true